### ISSUE TITLE
The packet loss rate is displayed abnormally

### ISSUE THREAD

**Issue by niyaodong** [syepes/network_exporter#10]
Hi @syepes ,

This is not a issue, I am Just a little confused.

On ICMP part, The packet loss rate is not normal on Grafana. (But packet loss is OK on MTR)

I compared the data and found that ping_loss_percent is float from 0 to 1, MTR packet loss is float from 0 to 100.

I am not sure if it is better to format ping_loss_percent as float from 0 to 100?

Looking forward your reply.

```
ping_loss_percent{name="google",target="8.8.8.8"} 0.5
```
```
mtr_rtt_seconds{name="8.8.8.8",path="8.8.8.8",target="8.8.8.8",ttl="12",type="loss"} 33.333335876464844
```

![image](https://user-images.githubusercontent.com/30104546/142347512-640a6b82-e163-44cc-989a-0ff8352dc084.png)
![image](https://user-images.githubusercontent.com/30104546/142347919-a8b33ecc-4ac3-4a9c-a8f0-947059f5a9ad.png)

**Comment by syepes** [comment]
@niyaodong Thanks for reporting this!
Actually a while ago I changed the ping loss unit from 100 -> 0.0 in the PR https://github.com/syepes/network_exporter/pull/5 but I had forgotten to also change the MTR loss units :-)

I have just updated the dashboards and fixed this in the code, images are getting built as you read this :-)

https://github.com/syepes/network_exporter/releases/tag/1.3.8

**Comment by niyaodong** [comment]
Hi Syepes,

The issue has been resolved!!! Thanks for such a quick response.
