### ISSUE TITLE
Panels display issues

### ISSUE THREAD

**Issue by niyaodong** [syepes/network_exporter#11]
Hi syepes,

It's me again...

I'm looking forward to deploying network_exporter in the production env as my leader was very satisfied with the monitoring stack. But I found something I am not able to deal with. so that I post it here.

1. It's not an issue. I would like to sort the items by ttl. I looked up a lot of information but couldn't find a way to do it.
![image](https://user-images.githubusercontent.com/30104546/142711356-d81f53f2-8242-45d6-bd28-72da36b59257.png)

2. Even if the node is unreachable, the panel still shows it.
In the time range shown below, hops 3-7 areunreachable, but they keep the same value like a straight line until they became reachable. this issue is not relevant to network_exporter as I checked network_exporter metircs were OK. Could it be caused by Victoriametrics?
![image](https://user-images.githubusercontent.com/30104546/142711632-70dc601f-5573-4aaa-850d-0a8846ff1dbc.png)

3. Invalid nodes will still be displayed.
As the panel shown below, we can see the hop 11 keeps updating. As I understand, currently the hop 11 should be "unknown" as the MTR shown below.
![image](https://user-images.githubusercontent.com/30104546/142712156-cf6331b6-53f8-45a0-a080-250db50afeb5.png)
![image](https://user-images.githubusercontent.com/30104546/142712173-ddb17c60-9ac1-4b1d-99bb-2c0b464b7f6a.png)

**Comment by niyaodong** [comment]
I found that issue 2 is solved if I delelte "keep_last_value" on panel Metrics browser setting.

```
sort(keep_last_value(avg_over_time(mtr_rtt_seconds{host=~"$station",name=~"$name_mtr", type="mean"}[$__interval])))
```
This is the explanation of “keep_last_value”，but I don't know the difference if I delete it.

```
keep_last_value(q) fills gaps with the value of the last non-empty point in every time series returned by q. 
```
![image](https://user-images.githubusercontent.com/30104546/142719892-d7fef8fc-36c9-4592-8f87-699e56d88802.png)
![image](https://user-images.githubusercontent.com/30104546/142719898-d5769aa9-155a-4f75-ad5a-a70909d99857.png)

**Comment by syepes** [comment]
old
