### ISSUE TITLE
Config question

### ISSUE THREAD

**Issue by MatzeP** [syepes/network_exporter#15]
Is it possible to configure also the Source IP + Port?
Now he only monitored the destination IP + Port.

**Comment by syepes** [comment]
Not as of right now, the source IP is the actual node were the exporter is running. So if your running multiple exporters from different locations, you can simply add the necessary [prometheus relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) with the IP.

**Comment by MatzeP** [comment]
Hi,
it would be an option but it is on my side not possible.
On my System, where the exporter runs, runs four application. These runs as Server and Client Applikation, so I want to monitored these.
