### ISSUE TITLE
[MTR] Why do all icmps loss except ttl=1 and ttl=max in mtr module?

### ISSUE THREAD

**Issue by qihonggang** [syepes/network_exporter#16]
![image](https://user-images.githubusercontent.com/9431724/154469368-45f07ccd-3215-498a-bcb6-34dc3d85ae17.png)

**Comment by qihonggang** [comment]
@syepes Please take a look, thanks！

**Comment by syepes** [comment]
There is much I can do about this, this means that from your ISP or the intermediate steps are not traceable
