### ISSUE TITLE
ping with source interface

### ISSUE THREAD

**Issue by ThomasSevestre** [syepes/network_exporter#21]
is it possible to ping via an interface?
something like `ping -I eth0 192.168.1.2`

**Comment by syepes** [comment]
Sorry but not as of right now, you can still achieve this by setting the default routing interface in you OS.
Check the `netstat -rn` and `route` commands.

**Comment by ThomasSevestre** [comment]
It does not work for my use cases but thanks for your answer.

**Comment by syepes** [comment]
No problem, just for curiosity could you give a bit more of details about your use case

**Comment by ThomasSevestre** [comment]
I have several virtual [routers](http://linux-ip.net/html/routing-tables.html) in a linux box. ping destinations are not reachable via main table.

I might also be needed to monitor linux namespaces but I'm not sure about that.

**Comment by Len4i** [comment]
another use case - is if you want to run a check via a specific line of your backbone where you have ECMP
For example:  
```
exporterA - router1 -- 2+ lines with ECMP -- router2 - target
``` 

So you can advertise specific /32 via line A, but you need to ensure that path back will also be chosen via the same line A
so you can take the exporter's source IP and advertise it only via lineA. All fine, but if you want to check multiple lines, you'll need to make sure that the exporter is probing a specific target with specific source IP.
