### ISSUE TITLE
Does writing two types of configuration support?

### ISSUE THREAD

**Issue by langlyyy** [syepes/network_exporter#23]
```
  - name: cloudflare-dns
    host: 1.1.1.1
    type: ICMP+MTR
```
If it is supported, why did I configure it that does not take effect?
![image](https://user-images.githubusercontent.com/29001120/167110382-aff11cd9-295e-443e-863a-cb5552757277.png)

**Comment by syepes** [comment]
This is supported, please try running the version [1.6.0](https://github.com/syepes/network_exporter/releases/tag/1.6.0) it contains some fixes
