### ISSUE TITLE
kubernetes mount network-exporter.yml file problem

### ISSUE THREAD

**Issue by ilanni2460** [syepes/network_exporter#25]
Thank you very much for having such an exporter. I plan to deploy the exporter to kubernetes, but I found that the network-exporter.yml file cannot be mapped to the pod through configmap, mainly because the file is mounted to the / root directory by default, may I ask this Is it possible to modify to other directory instead of root directory

deployment config:
`---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-exporter-configmap
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: network-exporter
    app.kubernetes.io/name: network-exporter
data:
    network-exporter.yml: |
      icmp:
        interval: 3s
        timeout: 1s
        count: 6
      
      mtr:
        interval: 3s
        timeout: 500ms
        max-hops: 30
        count: 6
      
      tcp:
        interval: 3s
        timeout: 1s
      
      http_get:
        interval: 15m
        timeout: 5s
      
      targets:
        - name: test_mtr
          host: 192.168.0.26
          type: MTR
        - name: test_tcp
          host: 192.168.0.26:1792
          type: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: network-exporter-svc
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: network-exporter
    app.kubernetes.io/name: network-exporter
spec:
  type: NodePort
  ports:
  - name: tcp-9427
    port: 1080
    protocol: TCP
  selector:
    app.kubernetes.io/instance: network-exporter
    app.kubernetes.io/name: network-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-exporter
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: network-exporter
    app.kubernetes.io/name: network-exporter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: network-exporter
      app.kubernetes.io/name: network-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: network-exporter
        app.kubernetes.io/name: network-exporter
    spec:
      containers:
      - name: network-exporter
        image: syepes/network_exporter:1.6.2
        imagePullPolicy: IfNotPresent
        args:
          - --config.file=/tmp/network-exporter.yml
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: network-exporter-conf
          mountPath: /tmp/
          readOnly: true
      volumes:
      - name: network-exporter-conf
        configMap:
          name: network-exporter-configmap
          items:
            - key: network-exporter.yml
              path: network-exporter.yml`

this is log:
`1s          Normal    SuccessfulCreate        pod/network-exporter-7c87b6f7c6-dwn4p    Created container network-exporter
1s          Warning   FailedStart             pod/network-exporter-7c87b6f7c6-dwn4p    Error: failed to start container "network-exporter": Error response from daemon: OCI runtime create failed: container_linux.go:318: starting container process caused "exec: \"--config.file=/tmp/network-exporter.yml\": stat --config.file=/tmp/network-exporter.yml: no such file or directory": unknown
0s          Warning   BackOffStart            pod/network-exporter-7c87b6f7c6-dwn4p    the failed container exited with ExitCode: 127
0s          Warning   BackOffStart            pod/network-exporter-7c87b6f7c6-dwn4p    Back-off restarting failed container`

**Comment by syepes** [comment]
I have not tried it under k8s, no problem I just pushed the [1.6.3](https://github.com/syepes/network_exporter/releases/tag/1.6.3) with the new config location /app/cfg/
