### ISSUE TITLE
The docker image of version 1.6.3 is invalid, it is still version 1.6.2.

### ISSUE THREAD

**Issue by ilanni2460** [syepes/network_exporter#26]
@syepes Thank you very much for your timely update, but I found that using The docker image of version 1.6.3 is invalid, it is still version 1.6.2.

this is log :
`
kubectl logs -f -n kube-system network-exporter-b4bc8dd9b-bdvh5 
ts=2022-11-04T15:52:01.558Z caller=main.go:54 level=info msg="Starting network_exporter" version=1.6.2
ts=2022-11-04T15:52:01.560Z caller=main.go:56 level=info msg="Loading config"
ts=2022-11-04T15:52:01.560Z caller=main.go:58 level=error msg="Loading config" err="reading config file: open /network_exporter.yml: no such file or directory"
`

**Comment by syepes** [comment]
Strange, give a try on the 1.6.4.

**Comment by ilanni2460** [comment]
@syepes Thank you very much, now it can run normally in k8s with the latest version 1.6.4, the attachment is the yml file deployed in k8s.
[network_exporter-deployment.zip](https://github.com/syepes/network_exporter/files/9945562/network_exporter-deployment.zip)
