### ISSUE TITLE
packet loss for ipv6 destinations

### ISSUE THREAD

**Issue by gilvia-layana** [syepes/network_exporter#29]
I'm having problems when I perform mtr to destinations that are ipv6.  Packet losses appear at hops along the way. when i stop the networ_exporter service the losses also stop. What can I do to resolve?
![image](https://user-images.githubusercontent.com/43282405/206201810-be83d62f-8aeb-47f8-963e-3d9d8408e211.png)
![image](https://user-images.githubusercontent.com/43282405/206201915-f02cff7b-8005-4617-a9f1-6c7f1956fc80.png)
![image](https://user-images.githubusercontent.com/43282405/206202194-73e5f8d5-52cb-4397-8c54-89db9a87e9a6.png)

**Comment by syepes** [comment]
This could be that something is blocking ICMP, currently the MTR implementation requires on ICMP (ping) to each of the routes.
