### ISSUE TITLE
Add an option to add static labels

### ISSUE THREAD

**Issue by guyellen** [syepes/network_exporter#3]
It would be great if we can add static labels for each target to enrich metadata:

for example:

targets:
  - name: internal
    host: 192.168.1.1
    type: ICMP
    **labels:
         isp_name: ispname
         label_test_1: test1**
  - name: google-dns1
    host: 8.8.8.8
    type: ICMP+MTR
    **labels:
         isp_name: ispname
         label_test_2: test2**

**Comment by syepes** [comment]
This is something I had partially implemented but forgotten to complete :-)
I'll finish it in the following weeks.
https://github.com/syepes/network_exporter/blob/master/config/config.go#L45

**Comment by cleonello** [comment]
Would be great to have this feature.   I would like to replace blackbox exporter with Network Exporter, but need to have this feature as we reference devices back to a unique host name and not the IP for monitoring purposes.

**Comment by Sangshaai** [comment]
Looking forward to this feature, may I ask when this feature will be available?

**Comment by syepes** [comment]
Last time I tried it was a bit more complex, I need to review how it could be done without changing everything :-)

**Comment by syepes** [comment]
Finally found some time to implement the target label support.
https://github.com/syepes/network_exporter/releases/tag/1.5.0
