### ISSUE TITLE
hope: The configure file same name in targets supports multiple ip probes

### ISSUE THREAD

**Issue by jxjy2016** [syepes/network_exporter#32]
hope: The configure file same name in targets supports multiple ip probes, and can support such ip probes:

targets:
 - name: idc_ 1
  host: 183.100.0.1
  host: 183.100.0.2
  host: 183.100.0.3
  host: 183.100.0.4
  type: ICMP
 - name: idc_ 2
  host: 204.152.0.1
  host: 204.152.0.2
  host: 204.152.0.3
  host: 204.152.0.4
  type: ICMP

thanks!~~

**Comment by syepes** [comment]
Sorry, but this won't be supported as it would change all the philosophy behind the tool.

You can achieve more or less the same thing right now using the SRV DNS records, lake a look at the readme:

https://github.com/syepes/network_exporter/blob/master/README.md?plain=1#L193
