### ISSUE TITLE
TCP+MTR type not supported

### ISSUE THREAD

**Issue by nondevops** [syepes/network_exporter#36]
TCP+MTR type not supported,Do you have a solution?
![image](https://user-images.githubusercontent.com/12181410/232811025-78b752b5-5cfa-4e4f-bf00-e9ebbe4a65a0.png)
![image](https://user-images.githubusercontent.com/12181410/232811692-6bcb03d8-acd3-4dcb-af52-90bbf28208d7.png)
![image](https://user-images.githubusercontent.com/12181410/232811771-5e84d41c-3786-4f2d-a189-e5ed6c5a510e.png)

**Comment by syepes** [comment]
Sorry, but for the moment the MTR is only implemented with ICMP, I won't be adding TCP support for performing the MTR's.

You can still use the standard TCP connection status and MTR together, you just need to specify the IP and PORT

`host:www.google.com:80`
