### ISSUE TITLE
What is the ID number of this Grafana template image? I hope you can share it with me

### ISSUE THREAD

**Issue by aliuzzz** [syepes/network_exporter#38]

**Comment by frydrahead** [comment]
Hello ! 
The dashboard is available here : https://github.com/syepes/network_exporter/blob/master/dist/deploy/cfg/provisioning/dashboards/network_exporter.json
As explained in the [Deployment Section](https://github.com/syepes/network_exporter#deployment)

**Comment by aliuzzz** [comment]
ok! tks and i will try it
