### ISSUE TITLE
Hello, syepes, ask questions

### ISSUE THREAD

**Issue by blackboar** [syepes/network_exporter#4]
icmp:
  interval: 3s
  timeout: 1s
  count: 6

How to understand interval and count in icmp parameter? How to write if I want to realize PING once per second?

**Comment by syepes** [comment]
interval <= This is the time the actual ping will run
timeout <= Timeout time it should wait for the ping to complete, Note it must be lower then the interval
count <= The total number of times the ping will execute, this will determine your stats (min,max,avg...) so it can not be to low

>PING once per second?
```
icmp:
interval: 1s
timeout: 800ms
count: 6
```
