### ISSUE TITLE
Problem Installation on Docker

### ISSUE THREAD

**Issue by mandud** [syepes/network_exporter#51]
Hi,

I just tried to install using docker, the result still failed
I've tried in 2 different machines, getting same error "/bin/sh: /app/network_exporter: Operation not permitted"

Thanks

**Comment by mandud** [comment]
Hi Sebastian,

I still newbie in installing docker application, currently I've tried to deploy from beginning
apps already running but I can't export it to grafana

![image](https://github.com/syepes/network_exporter/assets/3507479/9c0dc510-5673-4cbf-8e4c-6096efebeb3f)


Is there any full documentation for installing Network Exporter from beginning until fully works

Thanks

**Comment by jahknem** [comment]
Hey @mandud could you post how you got it to work instead of just saying it worked? I have a similar problem

**Comment by mandud** [comment]
Hi @jahknem I'm build using docker compose using this file https://github.com/syepes/network_exporter/tree/master/dist/deploy

thanks
