### ISSUE TITLE
custom metrics_path

### ISSUE THREAD

**Issue by wen-long** [syepes/network_exporter#55]
custom metrics_path can be used as a weak auth method and other purpose

prometheus support
```
# The HTTP resource path on which to fetch metrics from targets.
[ metrics_path: [<path>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#path) | default = /metrics ]
```

some other exporter supports metrics_path
https://github.com/prometheus/exporter-toolkit/pull/147
https://github.com/DLR-SC/repository-synergy/blob/115e48c37e659b144b2c3b89695483fd1d6dc788/data/readme_files/prometheus.snmp_exporter.md?plain=1#L50
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d865b6e7c113dcad1cbb3259eb7cb08855a48fb7/receiver/simpleprometheusreceiver/examples/federation/otel-collector-config.yml#L8
https://github.com/albertodonato/prometheus-aioexporter/blob/main/README.rst#exporter-command-line

**Comment by metanovii** [comment]
> custom metrics_path can be used as a weak auth method and other purpose
> 
> prometheus support
> 
> ```
> # The HTTP resource path on which to fetch metrics from targets.
> [ metrics_path: [<path>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#path) | default = /metrics ]
> ```
> 
> some other exporter supports metrics_path [prometheus/exporter-toolkit#147](https://github.com/prometheus/exporter-toolkit/pull/147) https://github.com/DLR-SC/repository-synergy/blob/115e48c37e659b144b2c3b89695483fd1d6dc788/data/readme_files/prometheus.snmp_exporter.md?plain=1#L50 https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d865b6e7c113dcad1cbb3259eb7cb08855a48fb7/receiver/simpleprometheusreceiver/examples/federation/otel-collector-config.yml#L8 https://github.com/albertodonato/prometheus-aioexporter/blob/main/README.rst#exporter-command-line

https://github.com/syepes/network_exporter/pull/59

**Comment by syepes** [comment]
https://github.com/syepes/network_exporter/pull/59
