### ISSUE TITLE
can i disable ipv6 entirely?

### ISSUE THREAD

**Issue by venkatamutyala** [syepes/network_exporter#56]
When doing ICMP requests against a hostname, it appears it can default to using ipv6 at times. Is there a way to disable ipv6 and only use ipv4?

**Comment by syepes** [comment]
resolved with [6cd26da](https://github.com/syepes/network_exporter/commit/6cd26daf5e1f13fc7b85165680b3e6428c403bac) that adds the option `--[no-]ipv6`

**Comment by venkatamutyala** [comment]
Yeaaaaaa

**Comment by 0megam** [comment]
I have tried to disable ipv6, but looks like `--no-ipv6` is not working:
```
/app # ps aux | grep network
    1 root      0:11 /app/network_exporter --no-ipv6
   98 root      0:00 grep network

/app # netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:35843        0.0.0.0:*               LISTEN      -
tcp        0      0 :::9427                 :::*                    LISTEN      1/network_exporter
udp        0      0 127.0.0.11:33579        0.0.0.0:*                           -
```
It looks like network_exporter is still binding to an IPv6 socket and is also trying to resolve AAAA records for the targets.
Am I missing something here?
