### ISSUE TITLE
docker-compose setcap error

### ISSUE THREAD

**Issue by danfoxley** [syepes/network_exporter#7]
Hello, 

Running the docker-compose deployment, I'm getting the following error both as root and non-root. Please help me resolve this issue.

ls
cfg  data  docker-compose.yml

docker-compose up
Creating network "deploy_data" with driver "bridge"
Creating volume "deploy_grafanadata" with default driver
Creating station1_agt ...
Creating station1_exporter ... error
Creating central_grafana   ...
Creating station1_agt      ... done

Creating central_grafana   ... done
 /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown

ERROR: for station1_exporter  Cannot start service station1_exporter: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.ipv4.ip_unprivileged_port_start: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by syepes** [comment]
@danfoxley This need to run as root or you need to give the container all the necessary privileges.
